FROM python:3.11-slim

RUN apt-get update && apt-get install -y cron

WORKDIR /app

COPY . /app/

RUN chmod +x /app/scripts/ingest.sh

RUN pip install --no-cache-dir -r requirements.txt

COPY crontab /etc/cron.d/ingest-cron
RUN chmod 0644 /etc/cron.d/ingest-cron
RUN crontab /etc/cron.d/ingest-cron

RUN touch /var/log/cron.log

RUN mkdir -p /app/data && chown -R 1000:1000 /app/data

CMD cron && tail -f /var/log/cron.log
